# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debug_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebugDialog(object):
    def setupUi(self, DebugDialog):
        DebugDialog.setObjectName("DebugDialog")
        DebugDialog.resize(300, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(DebugDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(DebugDialog)
        self.headerLabel.setStyleSheet("font-weight: bold; font-size: 14px;")
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.printElementsButton = QtWidgets.QPushButton(DebugDialog)
        self.printElementsButton.setObjectName("printElementsButton")
        self.verticalLayout.addWidget(self.printElementsButton)
        self.toggleViewButton = QtWidgets.QPushButton(DebugDialog)
        self.toggleViewButton.setObjectName("toggleViewButton")
        self.verticalLayout.addWidget(self.toggleViewButton)
        self.systemInfoButton = QtWidgets.QPushButton(DebugDialog)
        self.systemInfoButton.setObjectName("systemInfoButton")
        self.verticalLayout.addWidget(self.systemInfoButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.closeButton = QtWidgets.QPushButton(DebugDialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DebugDialog)
        QtCore.QMetaObject.connectSlotsByName(DebugDialog)

    def retranslateUi(self, DebugDialog):
        _translate = QtCore.QCoreApplication.translate
        DebugDialog.setWindowTitle(_translate("DebugDialog", "Debug Controls"))
        self.headerLabel.setText(_translate("DebugDialog", "Debug Actions"))
        self.printElementsButton.setText(_translate("DebugDialog", "Print Elements"))
        self.toggleViewButton.setText(_translate("DebugDialog", "Toggle View Mode"))
        self.systemInfoButton.setText(_translate("DebugDialog", "Show System Info"))
        self.closeButton.setText(_translate("DebugDialog", "Close"))
